config/routes.rb
VOSN::Application.routes.draw do
  match "voicemails/new" => "voicemails#create", :as => :new_voicemail, :via => :post
  resources :voicemails

  root :to => "voicemails#index"

end

app/models/voicemail.rb
class Voicemail < ActiveRecord::Base

  has_attached_file :attachment,
                    storage: :s3,
                    s3_credentials: {
                      access_key_id: S3[:key],
                      secret_access_key: S3[:secret]
                    },
                    bucket: S3[:bucket],
                    url: ':s3_southeast_url',
                    path: ':attachment/:id/:style.:extension'


  validates_attachment_presence :attachment

  def bitly_url
    Bitly.use_api_version_3
    bitly = Bitly.new(BITLY[:login], BITLY[:api_key])
    attachment_bitly = bitly.shorten(self.attachment.url)
    attachment_bitly.short_url
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate

  # Converts errors to array
  def errors_to_array(errors_hash)
    errors = []
    errors_hash.each do |error|
      errors << error[0].to_s.titleize + " " + error[1]
    end
    errors
  end

  protected
  def authenticate
    if params[:auth] && params[:auth][:username] == APP_AUTH[:username] && params[:auth][:password] == APP_AUTH[:password]
      true
    else
      head :unauthorized
      false
    end
  end
end

app/controllers/voicemails_controller.rb
class VoicemailsController < ApplicationController

  def index
    @voicemails = Voicemail.all
  end

  def new
    @voicemail = Voicemail.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml { render :xml => @voicemail }
    end
  end


  def create
    @voicemail = Voicemail.new(params[:voicemail])

    respond_to do |format|
      if @voicemail.save
        format.html { redirect_to(voicemails_path, :notice => 'Voice mail was successfully created.') }
        format.json do
          render :status => :created, :json => {
            :id => @voicemail.id,
            :bitly_url => @voicemail.bitly_url,
            :url => @voicemail.attachment.url,
            :attachment_file_name => @voicemail.attachment_file_name
          }
        end
      else
        format.html { render :action => 'new' }
        format.json { render :status => :unprocessable_entity, :json => {:errors => errors_to_array(@voicemail.errors)} }
      end
    end
  end

  def destroy
    @voicemail = Voicemail.find(params[:id])
    @voicemail.destroy

    respond_to do |format|
      format.html { redirect_to(voicemails_path, :notice => 'Voice mail was successfully deleted.') }
      format.xml { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/voicemails_helper.rb
module VoicemailsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>VOSN</title>
	<%= stylesheet_link_tag    "application" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/voicemails/index.html.erb
<h1>Listing Voicemails</h1>

<table>
  <tr>
    <th>Voicemail</th>
  </tr>

  <% @voicemails.each do |voicemail| %>
      <tr>
        <td><%= link_to voicemail.attachment_file_name, voicemail.attachment.url %></td>
        <td><%= link_to 'Destroy', voicemail, :confirm => 'Are you sure?', :method => :delete %></td>
      </tr>
  <% end %>
</table>

<br />

<%= link_to 'New Voicemail', new_voicemail_path %>

app/views/voicemails/new.html.erb
<h1>New Voicemail</h1>

<div class="notice"><%= notice %></div>

<% if @voicemail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@voicemail.errors.count, "error") %> prohibited this epic from being saved:</h2>

      <ul>
        <% @voicemail.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

<%= form_for(@voicemail, :html => { :multipart => true }) do |f| %>
    <p>
      <%= f.label :attachment %><br />
      <%= f.file_field :attachment %>
    </p>
    <p>
      <%= f.submit 'Upload' %>
    </p>
<% end %>

<%= link_to 'Back', voicemails_path %>